# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_3L0vJRiF5Nwf7fqerBlRAgMrWIvr3FE
"""

from google.colab import drive
drive.mount("/content/drive")
import pandas as pd

# Definimos la ruta de mi carpeta del drive
ruta_carpeta = "/content/drive/MyDrive/Colab Notebooks/"

# Cargamos los CSVs
cards = pd.read_csv(ruta_carpeta + "cards_data.csv")
users = pd.read_csv(ruta_carpeta + "users_data.csv")
transacciones = pd.read_csv(ruta_carpeta + "trasaccion final csv.txt")

# Comprobar que todo se cargó correctamente
print("Tarjetas cargadas:", cards.shape)
print("Usuarios cargados:", users.shape)
print("Transacciones cargadas:", transacciones.shape)

#1. Diagnóstico de la Integridad Estructural y Consistencia Relacional

cards['client_id'].nunique()

users['id'].nunique()

transacciones['client_id'].nunique()

#2. Depuración Metodológica y Resolución de Claves Compuestas


# 1. Filtrado de transacciones válidas (eliminamos clientes huérfanos)
clientes_validos = set(users["id"].astype(int))
transacciones = transacciones[
    transacciones["client_id"].astype(int).isin(clientes_validos)].copy()
print(f"Transacciones conservadas de clientes válidos: {len(transacciones):,}")
# 442,999 clientes válidos

# 2. Preparación de llaves para el cruce
# En transacciones: card_id puede traer vacíos (compras online de invitado)
transacciones["client_id_key"] = (transacciones["client_id"].astype(int).astype(str))
transacciones["card_id_key"] = (
    pd.to_numeric(transacciones["card_id"], errors="coerce")
    .fillna(-1)
    .astype(int)
    .astype(str))
transacciones["tarjeta_unica"] = (transacciones["client_id_key"] + "_" + transacciones["card_id_key"])

# En cards al tener dos pk, fusionamos dos en una.
cards["client_id_key"] = cards["client_id"].astype(int).astype(str)
cards["card_id_key"] = cards["id"].astype(int).astype(str)
cards["tarjeta_unica"] = cards["client_id_key"] + "_" + cards["card_id_key"]

# 3. Union
# Unión A: transacciones + cards (dejamos fuera columnas redundantes)
columnas_cards_a_cruzar = [col for col in cards.columns
    if col not in ["id", "client_id", "client_id_key", "card_id_key"]]
data = transacciones.merge(cards[columnas_cards_a_cruzar], on="tarjeta_unica", how="left")

# Union B: resultado + users
data = data.merge( users, left_on="client_id", right_on="id", how="left", suffixes=("", "_user"))

# 4. Eliminamos llaves temporales auxiliares
data.drop(columns=["client_id_key", "card_id_key", "id"],
    inplace=True,
    errors="ignore",)

# 6. Comprobación rápida de integridad
print("\n--- Verificación de nulos en datos de usuario ---")
print("Filas totales en 'data':", len(data))
print("Nulos en 'yearly_income':", data["yearly_income"].isna().sum())
print("Nulos en 'current_age':", data["current_age"].isna().sum())

#cards.isnull().sum() 0 valores nulos
#users.isnull().sum() 0 valores nulos
transacciones.isnull().sum() #card_id(8604), merchant_state(43748), zip(46731)

#3. Enriquecimiento Semántico: Normalización del Catálogo Comercial (MCC)


# 1. Leer mcc.txt cortando solo en la primera coma de cada línea
with open(ruta_carpeta + "mcc.txt", "r", encoding="utf-8") as f:
    lineas = f.readlines()

datos_mcc = [linea.strip().split(",", 1) for linea in lineas if "," in linea]
mcc = pd.DataFrame(datos_mcc[1:], columns=["mcc", "mcc_descripcion"])

# 2. Homologar claves a formato texto
data["mcc"] = data["mcc"].astype(str)
mcc["mcc"] = mcc["mcc"].astype(str)

# 3. Unir descripciones
data = data.merge(mcc, on="mcc", how="left")

print("Nulos restantes en 'mcc_descripcion':", data["mcc_descripcion"].isna().sum())
data[["transaction_id", "mcc", "mcc_descripcion"]].head(3)

#4. Normalización Numérica y Tipificación de Nulos Operacionales


# 1. Limpieza de columnas monetarias con símbolos de moneda o comas
columnas_moneda = ["credit_limit", "per_capita_income", "yearly_income", "total_debt"]

for col in columnas_moneda:
    if col in data.columns and data[col].dtype == "object":
        data[col] = (
            data[col]
            .astype(str)
            .str.replace("$", "", regex=False)
            .str.replace(",", "", regex=False)
            .str.strip())
        data[col] = pd.to_numeric(data[col], errors="coerce")

# 2. Asegurar que amount sea numérico
data["amount"] = pd.to_numeric(
    data["amount"].astype(str).str.replace("$", "", regex=False),
    errors="coerce")

# 3. Tratamiento de nulos propios de la operativa
# Flag para compras online como invitado (sin tarjeta física registrada en el sistema)
data["is_guest_online"] = (data["card_id"].isna() | (data["tarjeta_unica"].str.endswith("_-1"))).astype(int)

# Registros online sin estado geográfico ni código postal
data["merchant_state"] = data["merchant_state"].fillna("ONLINE")
data["zip"] = data["zip"].fillna(-1)

# Campos de tarjeta ausentes en compras online de invitado
data["card_brand"] = data["card_brand"].fillna("NO_CARD")
data["card_type"] = data["card_type"].fillna("NO_CARD")
data["has_chip"] = data["has_chip"].fillna("UNKNOWN")

print(f"Dimensiones de 'data': {data.shape}")
print("Nulos en 'yearly_income':", data["yearly_income"].isna().sum())
print("Nulos en 'amount':", data["amount"].isna().sum())

#5. Reconstrucción Temporal y Cinemática del Gasto

# 1. Construcción del timestamp uniendo fecha y hora
data["timestamp"] = pd.to_datetime(
    data["fecha"], format="mixed", dayfirst=True
) + pd.to_timedelta(data["hora"].fillna(0), unit="h")

# 2. Ordenación estricta por tarjeta y secuencia temporal
data = data.sort_values(by=["tarjeta_unica", "timestamp"]).reset_index(drop=True)

print("Primeras filas ordenadas:")
data[["tarjeta_unica", "timestamp", "amount", "merchant_state", "mcc_descripcion"]].head(3)

#6. Ingeniería de Características para la Detección de Patrones de Riesgo


# 1. Variables de tiempo individuales
data['hora_int'] = data['timestamp'].dt.hour
data['dia_semana'] = data['timestamp'].dt.dayofweek

# 2. Variables de velocidad entre compras de la misma tarjeta
# Desplazamos la fila previa dentro de cada tarjeta
data['prev_timestamp'] = data.groupby('tarjeta_unica')['timestamp'].shift(1)
data['prev_state'] = data.groupby('tarjeta_unica')['merchant_state'].shift(1)

# Diferencia en minutos respecto a la transacción anterior
data['diff_minutos'] = (data['timestamp'] - data['prev_timestamp']).dt.total_seconds() / 60.0
# Si es la primera compra registrada de la tarjeta, ponemos un valor neutro alto (ej. 999999 minutos)
data['diff_minutos'] = data['diff_minutos'].fillna(999999)

# Indicador de cambio de estado geográfico (excluyendo transacciones ONLINE)
estados_excluidos = ['ONLINE', 'UNKNOWN', 'nan', '', '-1', '-1.0']
data['cambio_estado_fisico'] = (
    (data['merchant_state'] != data['prev_state']) &
    (data['prev_state'].notnull()) &
    (~data['merchant_state'].astype(str).isin(estados_excluidos)) &
    (~data['prev_state'].astype(str).isin(estados_excluidos))
).astype(int)

# 3. Métricas de desviación sobre el gasto del usuario
# Gasto medio histórico de la tarjeta
media_gasto = data.groupby('tarjeta_unica')['amount'].transform('mean')
data['ratio_gasto_habitual'] = data['amount'] / (media_gasto + 1e-5)

# Ratio respecto al límite de crédito (si tiene límite positivo registrado)
data['ratio_credito'] = np.where(
    data['credit_limit'] > 0,
    data['amount'] / data['credit_limit'],
    0.0)

# 4. Limpieza de columnas temporales auxiliares
data.drop(columns=['prev_timestamp', 'prev_state'], inplace=True, errors='ignore')

# 5. Vista previa de las nuevas variables
print("--- Variables creadas con éxito ---")
data[['tarjeta_unica', 'timestamp', 'amount', 'diff_minutos', 'cambio_estado_fisico', 'ratio_gasto_habitual', 'ratio_credito']].head(5)

# Ver transacciones donde sí hubo gasto (amount > 0)
data[data['amount'] > 0][['tarjeta_unica', 'timestamp', 'amount', 'diff_minutos', 'ratio_gasto_habitual', 'ratio_credito']].head(5)

#7. Modelado No Supervisado Mediante Bosques de Aislamiento (Isolation Forest)

from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import IsolationForest

# 1. Selección de variables analíticas
features_num = [
    'amount',
    'hora_int',
    'dia_semana',
    'diff_minutos',
    'cambio_estado_fisico',
    'ratio_gasto_habitual',
    'ratio_credito',
    'current_age',
    'yearly_income',
    'total_debt',
    'credit_score'
]

# 2. Codificación One-Hot de categóricas relevantes
features_cat = ['use_chip', 'error_type']
df_modelo = pd.get_dummies(data[features_num + features_cat], columns=features_cat, drop_first=True)

# 3. Escalado de variables numéricas para normalizar magnitudes
scaler = StandardScaler()
X_scaled = scaler.fit_transform(df_modelo)

print(f"Matriz de características lista: {X_scaled.shape[0]:,} transacciones y {X_scaled.shape[1]} variables.")

# 1. Instanciación y entrenamiento del modelo
iso_forest = IsolationForest(
    n_estimators=100,
    contamination=0.02,
    random_state=42,
    n_jobs=-1)

# 2. Predicción (-1 = anomalía/fraude, 1 = normal)
predicciones = iso_forest.fit_predict(X_scaled)
data['es_fraude_predicho'] = np.where(predicciones == -1, 1, 0)

# 3. Obtención del score de anomalía (cuanto más bajo/negativo, mayor riesgo)
data['anomaly_score'] = iso_forest.decision_function(X_scaled)

# 4. Reporte de detecciones
total_fraudes = data['es_fraude_predicho'].sum()
porcentaje = (total_fraudes / len(data)) * 100
print("--- RESULTADOS DEL MODELO ANOMALÍAS (ISOLATION FOREST) ---")
print(f"Transacciones analizadas: {len(data):,}")
print(f"Transacciones anómalas (posible fraude): {total_fraudes:,} ({porcentaje:.2f}%)")
print(f"Transacciones normales: {(len(data) - total_fraudes):,} ({(100 - porcentaje):.2f}%)")

# Top 5 transacciones más anómalas
top_anomalias = data[data['es_fraude_predicho'] == 1].sort_values(by='anomaly_score').head(5)
top_anomalias[['tarjeta_unica', 'timestamp', 'amount', 'ratio_gasto_habitual', 'diff_minutos', 'mcc_descripcion', 'anomaly_score']]

#9. Análisis de la Distribución del Gasto y Detección de Desviaciones Atípicas

import matplotlib.pyplot as plt
import seaborn as sns

# Configuración visual
sns.set_theme(style="whitegrid")
fig, axes = plt.subplots(1, 2, figsize=(15, 5))

# Gráfico 1: Comparación de montos (Normales vs Sospechosas)
sns.boxplot(
    data=data,
    x='es_fraude_predicho',
    y='amount',
    showfliers=False,
    palette=['#2b5c8f', '#d9534f'],
    ax=axes[0])
axes[0].set_title('Distribución de Monto: Normales (0) vs. Sospechosas (1)')
axes[0].set_xlabel('Clasificación del Modelo')
axes[0].set_ylabel('Monto ($)')
axes[0].set_xticklabels(['Normal', 'Anómala / Riesgo'])

# Gráfico 2: Desviación respecto al gasto habitual
sns.scatterplot(
    data=data.sample(5000, random_state=42), # Muestra de 5000 puntos para no saturar
    x='amount',
    y='ratio_gasto_habitual',
    hue='es_fraude_predicho',
    palette=['#2b5c8f', '#d9534f'],
    alpha=0.6,
    ax=axes[1])
axes[1].set_title('Monto vs. Ratio de Gasto Habitual')
axes[1].set_xlabel('Monto ($)')
axes[1].set_ylabel('Ratio de Gasto (Veces sobre su media)')
axes[1].set_ylim(0, 20)

plt.tight_layout()
plt.show()

# Resumen numérico de comparación
print("--- COMPARATIVA DE PERFILES (MEDIAS) ---")
print(data.groupby('es_fraude_predicho')[['amount', 'ratio_gasto_habitual', 'diff_minutos', 'ratio_credito']].mean())

#10. Comprobar una trasacción sospechosa

import numpy as np
import pandas as pd

# 1. Definir los datos de la nueva transacción sospechosa que quieres probar
# Ejemplo: Compra de 2,500 $ a las 3 AM (madrugada), pasaron solo 2 minutos desde la compra anterior,
# en un estado físico diferente, gastando 8 veces más de lo habitual y agotando el 90% del límite de crédito.
nueva_transaccion_dict = {
    'amount': 2500.0,
    'hora_int': 3,
    'dia_semana': 5,                   # Sábado
    'diff_minutos': 2.0,               # Solo 2 minutos de diferencia
    'cambio_estado_fisico': 1,         # Compró en otro estado
    'ratio_gasto_habitual': 8.5,       # 8.5 veces más caro de lo normal
    'ratio_credito': 0.90,             # 90% de su límite de crédito
    'current_age': 42,
    'yearly_income': 45000.0,
    'total_debt': 12000.0,
    'credit_score': 620.0,
    'use_chip': 'Swipe Transaction',   # Banda magnética
    'error_type': 'Bad PIN'            # Fallo de PIN
}

# 2. Convertir a DataFrame
df_nueva = pd.DataFrame([nueva_transaccion_dict])

# 3. Aplicar One-Hot Encoding alineado exactamente con el dataset de entrenamiento
df_nueva_encoded = pd.get_dummies(df_nueva, columns=['use_chip', 'error_type'], drop_first=True)

# Asegurar que tenga exactamente las mismas columnas que 'df_modelo' (rellenando con 0 las categorías ausentes)
df_nueva_encoded = df_nueva_encoded.reindex(columns=df_modelo.columns, fill_value=0)

# 4. Escalar los datos usando el MISMO escalador del entrenamiento
nueva_scaled = scaler.transform(df_nueva_encoded)

# 5. Realizar la predicción con Isolation Forest
prediccion = iso_forest.predict(nueva_scaled)[0]           # -1 = Anomalía / Fraude, 1 = Normal
score_riesgo = iso_forest.decision_function(nueva_scaled)[0] # Cuanto más negativo, mayor es el riesgo

# 6. Mostrar el resultado interpretado
resultado_texto = "¡ALERTA DE POSIBLE FRAUDE!" if prediccion == -1 else "Transacción Normal"

print("==================================================")
print("--- RESULTADO DE LA PREDICCIÓN TRANSACCIONAL ---")
print("==================================================")
print(f"Diagnóstico del modelo : {resultado_texto}")
print(f"Puntaje de anomalía    : {score_riesgo:.4f}")
print("Nota: Un puntaje negativo indica que la operación se desvía drásticamente del patrón habitual.")
print("==================================================")

#11. Evaluación Estadística, Probabilística y Distribución Temporal del Riesgo

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.special import expit  # Función logística para probabilidad

# 1. Probabilidad aplicada: Transformación del anomaly_score a escala [0, 1]
# Cuanto más negativo el score, mayor es la probabilidad de riesgo
data['probabilidad_fraude'] = expit(-data['anomaly_score'] * 10)

# Probabilidad condicionada por tipo de canal (use_chip)
prob_canal = data.groupby('use_chip')['es_fraude_predicho'].mean().rename("P(Fraude | Canal)")
print("--- PROBABILIDAD CONDICIONADA POR CANAL ---")
print(prob_canal)

# 2. Análisis descriptivo comparativo de comportamientos
print("\n--- COMPORTAMIENTO MEDIO: NORMAL vs. FRAUDE ---")
comparativa = data.groupby('es_fraude_predicho')[[
    'amount',
    'diff_minutos',
    'ratio_gasto_habitual',
    'ratio_credito',
    'probabilidad_fraude'
]].mean()
print(comparativa)

# 3. Correlaciones y Distribuciones
plt.figure(figsize=(10, 6))
cols_corr = ['amount', 'diff_minutos', 'ratio_gasto_habitual', 'ratio_credito', 'credit_score', 'anomaly_score']
corr_matrix = data[cols_corr].corr()

sns.heatmap(corr_matrix, annot=True, fmt='.2f', cmap='coolwarm', linewidths=0.5)
plt.title('Matriz de Correlación: Variables Clave vs. Score de Anomalía')
plt.tight_layout()
plt.show()

# 4. Tendencias horarias
plt.figure(figsize=(10, 4))
sns.countplot(data=data, x='hora_int', hue='es_fraude_predicho', palette=['#1f77b4', '#d62728'])
plt.title('Distribución de Transacciones por Hora del Día')
plt.xlabel('Hora')
plt.ylabel('Cantidad')
plt.legend(['Normal', 'Sospechoso'])
plt.tight_layout()
plt.show()